# Generated by Django 2.1.7 on 2019-03-23 12:50

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=1000)),
                ('resume_title', models.CharField(max_length=1000)),
                ('resume', models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/storage/resume'), upload_to='')),
                ('type', models.BooleanField(default=False)),
            ],
        ),
    ]
