# Generated by Django 2.1.7 on 2019-03-23 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_auto_20190323_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobuser',
            name='description',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='jobuser',
            name='resume',
            field=models.FileField(upload_to='resume/'),
        ),
    ]
