# Generated by Django 2.1.7 on 2019-03-23 16:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_auto_20190323_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobuser',
            name='created_datetime',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 23, 22, 0, 34, 404082)),
        ),
    ]
