# Generated by Django 2.1.7 on 2019-03-23 17:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0007_auto_20190323_2207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobuser',
            name='type',
        ),
        migrations.AlterField(
            model_name='jobuser',
            name='created_datetime',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 23, 22, 51, 29, 517895)),
        ),
    ]
